apiVersion: v1

kind: Pod

metadata:
  name: nginx-2
  labels:
    app: nginx-2
    env: prod

spec:
  containers:
    - name: nginx-2
      image: nginx:latest
      env:
        - name: THE_SECRET
          value: mysecretpassword