apiVersion: v1

kind: ReplicationController

metadata:
  name: nginx-rc
  labels:
    app: nginx
    type: front-end

spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
        type: front-end

    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          
  replicas: 3
